import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache images
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
    })
);

// Cache API responses (optional, for metadata)
registerRoute(
    ({ url }) => url.origin === 'https://www.googleapis.com',
    new NetworkFirst({
        cacheName: 'youtube-api',
    })
);

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
